CREATE TABLE backpackd_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    user_email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE
    backpackd_backpacks
ADD
    COLUMN user_id INTEGER REFERENCES backpackd_users(id) ON DELETE CASCADE NOT NULL;